version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  test:
    docker:
      - image: cimg/python:3.11.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: poetry run pytest tests/unit/ -v
      - run:
          name: Run linting
          command: |
            poetry run black --check snowflake_semantic_tools/
            poetry run isort --check snowflake_semantic_tools/

  build-and-publish:
    docker:
      - image: cimg/python:3.11.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Build package
          command: poetry build
      # TODO: Uncomment when PyPI token is configured in CircleCI
      # - run:
      #     name: Publish to PyPI
      #     command: |
      #       poetry config pypi-token.pypi ${PYPI_TOKEN}
      #       poetry publish --skip-existing

workflows:
  build_test_deploy:
    jobs:
      - test
      - hold-for-approval:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: main
      - build-and-publish:
          requires:
            - hold-for-approval
          filters:
            branches:
              only: main
